# Generated by Django 4.1.3 on 2022-11-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'get_latest_by': 'upload_date'},
        ),
    ]
